#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Jan 26, 2019 04:41:00 PM +0800  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 803x539+503+171
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "News Headline Sentiment Analysis"
    vTcl:DefineAlias "$top" "SA" vTcl:Toplevel:WidgetProc "" 1
    button $top.but66 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Exit 
    vTcl:DefineAlias "$top.but66" "Button3" vTcl:WidgetProc "SA" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo49 \
        -width 754 -height 441 -takefocus {} 
    vTcl:DefineAlias "$top.tNo49" "TNotebook1" vTcl:WidgetProc "SA" 1
    frame $top.tNo49.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t0" "TNotebook1_t0" vTcl:WidgetProc "SA" 1
    $top.tNo49 add $top.tNo49.t0 \
        -padding 0 -sticky nsew -state normal \
        -text {Sentiment Analysis for File} -image {} -compound left \
        -underline -1 
    set site_4_0  $top.tNo49.t0
    label $site_4_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {News Headlines File :} 
    vTcl:DefineAlias "$site_4_0.lab59" "Label4" vTcl:WidgetProc "SA" 1
    entry $site_4_0.ent60 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent60" "Entry2" vTcl:WidgetProc "SA" 1
    button $site_4_0.but61 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Clear 
    vTcl:DefineAlias "$site_4_0.but61" "Button4" vTcl:WidgetProc "SA" 1
    button $site_4_0.but62 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$site_4_0.but62" "Button5" vTcl:WidgetProc "SA" 1
    button $site_4_0.but63 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Submit 
    vTcl:DefineAlias "$site_4_0.but63" "Button6" vTcl:WidgetProc "SA" 1
    place $site_4_0.lab59 \
        -in $site_4_0 -x 30 -y 130 -anchor nw -bordermode ignore 
    place $site_4_0.ent60 \
        -in $site_4_0 -x 210 -y 130 -width 484 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but61 \
        -in $site_4_0 -x 330 -y 240 -width 86 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but62 \
        -in $site_4_0 -x 470 -y 240 -width 80 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but63 \
        -in $site_4_0 -x 610 -y 240 -width 89 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo49.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t1" "TNotebook1_t1" vTcl:WidgetProc "SA" 1
    $top.tNo49 add $top.tNo49.t1 \
        -padding 0 -sticky nsew -state normal \
        -text {Sentiment Analysis for News} -image {} -compound left \
        -underline -1 
    set site_4_1  $top.tNo49.t1
    label $site_4_1.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {News Headline :} 
    vTcl:DefineAlias "$site_4_1.lab50" "Label1" vTcl:WidgetProc "SA" 1
    entry $site_4_1.ent51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_1.ent51" "Entry1" vTcl:WidgetProc "SA" 1
    button $site_4_1.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Clear 
    vTcl:DefineAlias "$site_4_1.but52" "Button1" vTcl:WidgetProc "SA" 1
    button $site_4_1.but53 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Submit 
    vTcl:DefineAlias "$site_4_1.but53" "Button2" vTcl:WidgetProc "SA" 1
    frame $site_4_1.fra54 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 175 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 655 
    vTcl:DefineAlias "$site_4_1.fra54" "Frame1" vTcl:WidgetProc "SA" 1
    set site_5_0 $site_4_1.fra54
    label $site_5_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Sentiment Analysis Result :} 
    vTcl:DefineAlias "$site_5_0.lab55" "Label2" vTcl:WidgetProc "SA" 1
    text $site_5_0.tex56 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 244 -wrap word 
    .top42.tNo49.t1.fra54.tex56 configure -font TkTextFont
    .top42.tNo49.t1.fra54.tex56 insert end text
    vTcl:DefineAlias "$site_5_0.tex56" "Text1" vTcl:WidgetProc "SA" 1
    label $site_5_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Sentiment Analysis Probability :} 
    vTcl:DefineAlias "$site_5_0.lab57" "Label3" vTcl:WidgetProc "SA" 1
    text $site_5_0.tex58 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 244 -wrap word 
    .top42.tNo49.t1.fra54.tex58 configure -font TkTextFont
    .top42.tNo49.t1.fra54.tex58 insert end text
    vTcl:DefineAlias "$site_5_0.tex58" "Text2" vTcl:WidgetProc "SA" 1
    place $site_5_0.lab55 \
        -in $site_5_0 -x 40 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.tex56 \
        -in $site_5_0 -x 280 -y 30 -width 244 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab57 \
        -in $site_5_0 -x 30 -y 100 -width 232 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tex58 \
        -in $site_5_0 -x 280 -y 110 -width 244 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab50 \
        -in $site_4_1 -x 40 -y 50 -width 123 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent51 \
        -in $site_4_1 -x 200 -y 50 -width 494 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but52 \
        -in $site_4_1 -x 500 -y 110 -width 76 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but53 \
        -in $site_4_1 -x 630 -y 110 -width 76 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra54 \
        -in $site_4_1 -x 50 -y 200 -width 655 -relwidth 0 -height 175 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but66 \
        -in $top -x 670 -y 490 -width 96 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo49 \
        -in $top -x 30 -y 30 -width 754 -relwidth 0 -height 441 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

